/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
static yyconst short int yy_accept[383] =
    {   0,
        0,    0,   94,   92,   91,   91,   77,   92,   92,   75,
       92,   92,   69,   72,   70,   71,   92,   73,   80,   80,
       78,   67,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   68,   68,    0,   88,   76,    0,
       74,    0,    0,   80,   80,   84,   84,   82,    0,    0,
        0,    0,   80,   89,   89,   89,   89,    4,    0,   89,
       89,   89,   89,   89,   89,   16,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   37,   89,
       89,   89,   89,   89,   89,   48,   89,   89,   89,   89,

       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       87,   88,   86,    0,    0,   84,    0,   85,   83,   81,
       89,    2,   89,    0,    0,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   15,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   32,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   47,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   60,   89,   62,   63,
       89,   65,   89,   89,    0,    0,   89,   89,   89,    0,
       89,   89,    7,   89,   89,   89,   89,   89,   89,   89,
       17,   18,   89,   89,   89,   89,   89,   89,   27,   28,

       89,   89,   89,   89,   89,   89,   36,   89,   89,   89,
       89,   89,   45,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   79,   89,   89,   89,   89,    0,
       89,    3,    5,   89,    8,    9,   10,   11,   89,   89,
       89,   89,   20,   89,   89,   24,   89,   89,   89,   30,
       89,   89,   89,   89,   89,   89,   89,   89,   44,   89,
       49,   89,   89,   89,   89,   89,   89,   89,   58,   59,
       61,   64,   66,   89,   89,   89,   89,   89,   89,   19,
       89,   22,   89,   89,   89,   89,   89,   89,   35,   89,
       89,   89,   89,   89,   89,   89,   89,   52,   89,   55,

       56,   57,   89,   89,   89,   89,   13,   14,   89,   89,
       89,   89,   29,   31,   33,   89,   89,   39,   89,   89,
       89,   89,   50,   89,   89,    0,    1,    6,   12,   89,
       89,   89,   26,   34,   89,   89,   89,   89,   89,   89,
       89,   53,    0,    0,   89,   89,   25,   89,   89,   89,
       42,   43,   46,   51,   89,    0,    0,   21,   23,   38,
       89,   41,   89,    0,    0,    0,   89,   89,    0,   40,
       89,    0,    0,    0,   54,    0,    0,    0,    0,   90,
       90,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,    1,   23,    1,
       24,    1,    1,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   34,
       50,    1,   51,    1,   52,    1,   25,   53,   27,   54,

       55,   56,   31,   32,   57,   34,   35,   36,   37,   58,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   34,   59,   60,   59,    1,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,

       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    1,    1,    6,    6,    6,    6,    6,    6,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    8,
        1,    7,    6,    6,    6,    6,    7,    7,    1,    1
    } ;

static yyconst short int yy_base[395] =
    {   0,
        0,    0,  979,  980,  980,  980,  980,    0,    0,  980,
      969,    0,  980,  964,   47,   56,   60,  980,   66,   72,
      980,  980,   70,   48,   79,   93,  103,  113,   61,  926,
      117,   74,  137,   60,   92,  127,   59,  136,  121,   49,
       85,   66,  124,  151,  980,  980,  969,    0,  980,  964,
      980,  174,  178,    0,  190,  194,  205,  211,  222,  234,
        0,  125,  242,  923,  122,  218,   83,  922,  183,  223,
      231,  197,  179,  249,  236,  921,  188,  126,  230,  254,
      233,  252,  185,  256,  242,  257,  248,   21,  920,  250,
      274,  260,  269,  276,  138,  919,  283,  285,  279,  296,

      292,  286,  302,  287,  303,  289,  310,  306,  315,  327,
      962,    0,  957,  342,  352,  365,  369,  376,    0,  269,
      139,  916,  309,  914,  380,  316,  332,  363,  328,  360,
      366,  362,  343,  325,  914,  369,  380,  367,  393,  378,
      383,  396,  372,  404,  403,  407,  411,  402,  406,  409,
      394,  410,  419,  418,  426,  913,  425,  422,  434,  428,
      432,  435,  436,  448,  455,  460,  912,  461,  911,  910,
      456,  909,  457,  469,  480,  501,  453,  447,  980,  512,
      478,  479,  908,  486,  474,  496,  464,  504,  502,  493,
      907,  507,  492,  510,  505,  517,  498,  518,  906,  905,

      520,  524,  526,  534,  522,  544,  904,  542,  530,  552,
      540,  539,  903,  543,  541,  562,  559,  563,  565,  553,
      566,  574,  558,  556,  902,  560,  582,  589,  568,  609,
      594,  901,  900,  595,  899,  898,  897,  896,  596,  583,
      591,  605,  895,  609,  600,  894,  616,  618,  624,  617,
      613,  627,  620,  621,  629,  631,  622,  632,  893,  636,
      892,  641,  653,  660,  661,  654,  667,  663,  891,  890,
      889,  888,  887,  643,  669,  664,  652,  670,  657,  886,
      672,  676,  665,  682,  678,  674,  695,  690,  885,  701,
      704,  707,  708,  710,  713,  714,  697,  884,  700,  883,

      882,  881,  207,  702,  715,  724,  880,  879,  723,  730,
      722,  732,  878,  877,  876,  728,  733,  687,  738,  742,
      748,  749,  875,  739,  755,  370,  874,  873,  866,  735,
      763,  764,  858,  849,  751,  758,  761,  772,  774,  775,
      781,  765,    0,    0,  777,  784,  828,  769,  783,  788,
      818,  814,  813,  812,  787,  847,  840,  792,  757,  656,
      793,  615,  798,  534,  485,  457,  810,  796,  841,  295,
      811,  848,    0,    0,  243,  263,  126,  843,  847,   78,
       52,  980,  866,  869,  876,  880,  884,  887,  888,  890,
      895,  899,  906,  914

    } ;

static yyconst short int yy_def[395] =
    {   0,
      382,    1,  382,  382,  382,  382,  382,  383,  384,  382,
      382,  385,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  382,  382,  383,  387,  382,  385,
      382,  382,  382,   19,  382,  382,  382,  382,  382,  382,
      388,  382,  382,  386,  386,  386,  386,  386,  382,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      383,  387,  385,  382,  382,  382,  382,  382,  388,  382,
      386,  386,  386,  382,  382,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  382,  382,  386,  386,  382,  382,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  382,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  382,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  389,  390,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  391,  392,  386,  386,  386,
      386,  386,  386,  382,  391,  392,  386,  386,  382,  386,
      386,  382,  393,  394,  386,  393,  394,  393,  394,  393,
      394,    0,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382

    } ;

static yyconst short int yy_nxt[1041] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   13,   14,   15,    4,   16,   17,   18,   19,   20,
       20,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   30,   30,   32,   30,   33,   34,   35,
       30,   36,   37,   38,   39,   40,   41,   42,   43,    4,
        4,   30,   24,   44,   27,   28,   31,   33,   45,   46,
       52,  379,   52,   53,  148,   54,   55,   55,   55,   52,
       69,   52,   53,  106,   54,   55,   55,   55,   56,   56,
       56,   56,   57,  378,   58,   58,   58,   59,   57,   70,
       63,   63,   63,   63,   60,   65,   87,   69,   69,   88,

       60,   96,  100,   71,  108,  101,   93,   66,   69,   69,
       69,   67,   68,   61,   72,   69,  107,   73,   62,   69,
       60,   74,   65,   69,  123,   75,   60,   66,   69,   77,
       93,   76,   69,   97,   69,  379,   98,   83,   78,   79,
       80,   69,   69,  120,  120,   84,   89,   74,   81,   75,
       82,   85,   69,   90,   91,   99,  109,   86,  104,   92,
       80,   94,   69,  105,  121,   95,   69,  102,  137,   84,
       69,   69,   89,   69,   91,   69,   69,  103,  104,   74,
      109,   99,  177,   75,  156,   69,   69,   69,   69,   76,
      114,   95,  115,  115,  115,  115,   56,   56,   56,   56,

       69,  124,  125,  125,  125,  110,   57,   75,   63,   63,
       63,   63,   56,   56,   56,   56,  132,  326,   60,  136,
      143,  130,   60,  116,  116,  116,  116,   57,   69,   58,
       58,   58,   59,   60,   69,  131,  132,   69,   57,   60,
       59,   59,   59,   59,   60,  122,   69,  117,   60,  117,
       60,  126,  118,  118,  118,  118,   69,  140,   57,   60,
       63,   63,   63,   63,  135,   60,  127,   69,  378,  138,
       60,  122,   69,  128,  129,  133,   60,  126,  134,   69,
       69,  139,   69,  145,  141,   69,  147,  120,  120,  149,
      135,   69,   69,  144,  146,  142,   60,   69,   69,   69,

      150,   69,  153,   69,  134,   69,   69,  139,  141,   69,
      159,  154,  155,  144,  146,  157,  151,  152,   69,  160,
      162,  158,  161,   69,  163,   69,  165,  164,   69,  168,
      170,  169,   69,  178,   69,   69,   69,  159,   69,  157,
      181,   69,  171,  173,   69,   69,  166,  172,  163,  190,
      167,   69,   69,  133,  184,   69,  134,  169,   69,   69,
      175,  175,  175,  175,   69,   69,  171,  182,  176,  173,
      115,  115,  115,  115,   69,  343,   69,   69,  189,  344,
       60,   69,  174,  116,  116,  116,  116,  118,  118,  118,
      118,  183,   69,   60,  118,  118,  118,  118,  180,  180,

      180,  180,  185,  186,  187,  188,   60,  191,  192,   69,
      193,   69,   69,  199,  202,   69,   69,  183,   69,   60,
      194,   69,  195,  186,  201,  196,  200,   69,  203,   69,
      179,  204,   69,  205,  192,  197,  206,  210,  211,  198,
      207,  208,   69,   69,  209,   69,  194,  212,  195,  196,
      201,   69,   69,   69,  214,   69,   69,  204,   69,   69,
       69,  213,  215,  206,  211,  217,  364,   69,   69,  218,
      216,   69,  219,  212,   69,   69,  220,   69,  221,  222,
      214,   69,  215,   69,   69,   69,  223,  224,  225,  226,
      364,  227,  228,  190,  231,  232,   69,   69,  175,  175,

      175,  175,   69,  234,   69,   69,   69,  238,   60,   69,
       69,  224,  233,   69,  225,  226,  236,  235,   69,  230,
      230,  230,  230,   69,  237,  229,  240,   69,   69,   60,
      180,  180,  180,  180,   60,   69,  239,  241,  244,  242,
      243,   69,   69,  245,  247,   69,  246,   69,  369,  248,
      237,   69,  225,   69,   69,   60,   69,  249,  251,   69,
      239,  250,  179,  242,  244,  252,   69,   69,  253,   69,
      254,   69,  246,   69,  255,   69,  256,  249,  225,   69,
      257,  258,  259,   69,  261,  260,  262,  263,   69,   69,
       69,   69,   69,   69,  266,  264,  254,  265,  267,  270,

      268,   69,   69,  271,  269,   69,  257,   69,   69,   69,
      272,   69,   69,  263,   69,   69,  273,   69,  275,  264,
      276,  265,  267,   69,  278,  274,  279,  230,  230,  230,
      230,   69,   69,  277,  280,  281,  272,   60,   69,  287,
       69,  282,  273,   69,   69,   69,  293,  276,  283,   69,
      284,  285,  286,  277,   69,  289,  291,  290,   69,  288,
      280,  294,   69,   60,   69,   69,   69,   69,  292,   69,
       69,   69,  283,   69,  284,  295,   69,  285,   69,  297,
       69,   69,  291,  288,  296,   69,  298,  294,  292,  299,
       69,  300,   69,  301,  302,  304,  306,  303,  307,  305,

      308,   69,   69,   69,  310,   69,   69,  309,  311,   69,
       69,  300,   69,   69,   69,  299,   69,  312,   69,   69,
      313,   69,  314,   69,  307,   69,  315,   69,  316,  317,
      310,   69,  318,  319,  321,  320,   69,  322,  336,   69,
      324,  325,  323,  328,   69,  327,   69,  330,  332,   69,
       69,   69,  329,   69,  331,  317,   69,   69,  318,   69,
      333,  320,   69,   69,   69,  334,  337,  341,  323,  328,
      335,   69,   69,   69,  339,  340,  345,   69,  329,   69,
      338,   69,   69,  342,   69,  334,  333,   69,   69,  346,
      335,   69,  337,  341,  348,  347,  349,   69,   69,  350,

       69,  351,  352,  353,   69,  358,   69,   69,  354,  342,
       69,  360,   69,   69,   69,  359,  355,  362,   69,  367,
      361,   69,  371,   69,   69,  363,   69,  351,  352,  353,
       69,  358,   69,   69,  354,  368,   69,   69,  370,  375,
      361,   69,   69,  362,  372,   69,  373,   69,  378,  364,
      374,  372,  364,  373,  380,  368,  379,  374,  381,   69,
       69,   69,   69,   69,  370,  375,   47,   69,   47,   47,
       47,   47,   47,   47,   48,   48,   50,   69,   50,   50,
       50,   50,   50,   50,   64,   64,   64,   64,  112,  112,
      112,  119,  119,  356,  356,  357,  357,  365,   69,  365,

      365,  365,  366,  366,  366,  366,  376,   69,  376,  376,
      376,  376,  376,  376,  377,   69,  377,  377,  377,  377,
      377,  377,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,  179,   69,  113,  111,   69,   69,
       69,   69,   69,  113,  111,   69,   51,   49,  382,    3,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,

      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382
    } ;

static yyconst short int yy_chk[1041] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       15,  381,   15,   15,   88,   15,   15,   15,   15,   16,
       88,   16,   16,   40,   16,   16,   16,   16,   17,   17,
       17,   17,   19,  380,   19,   19,   19,   19,   20,   24,
       20,   20,   20,   20,   19,   23,   29,   24,   40,   29,

       20,   34,   37,   25,   42,   37,   32,   23,   37,   34,
       29,   23,   23,   19,   25,   42,   41,   25,   19,   23,
       19,   26,   23,   32,   67,   26,   20,   23,   25,   27,
       32,   26,   67,   35,   41,  377,   35,   28,   27,   27,
       27,   35,   26,   62,   62,   28,   31,   26,   27,   26,
       27,   28,   27,   31,   31,   36,   43,   28,   39,   31,
       27,   33,   28,   39,   65,   33,   31,   38,   78,   28,
       39,   65,   31,   43,   31,   78,   36,   38,   39,   44,
       43,   36,  121,   44,   95,   38,   33,   95,  121,   44,
       52,   33,   52,   52,   52,   52,   53,   53,   53,   53,

       44,   69,   69,   69,   69,   44,   55,   44,   55,   55,
       55,   55,   56,   56,   56,   56,   73,  303,   55,   77,
       83,   72,   56,   57,   57,   57,   57,   58,   73,   58,
       58,   58,   58,   57,   83,   72,   73,   77,   59,   58,
       59,   59,   59,   59,   55,   66,   72,   60,   56,   60,
       59,   70,   60,   60,   60,   60,  303,   81,   63,   57,
       63,   63,   63,   63,   75,   58,   71,   66,  376,   79,
       63,   66,   70,   71,   71,   74,   59,   70,   74,   79,
       71,   80,   81,   85,   82,   75,   87,  120,  120,   90,
       75,   85,  375,   84,   86,   82,   63,   87,   74,   90,

       91,   82,   92,   80,   74,   84,   86,   80,   82,   92,
       98,   93,   94,   84,   86,   97,   91,   91,   93,   99,
      100,   97,   99,   91,  101,   94,  103,  102,   99,  104,
      106,  105,   97,  123,   98,  102,  104,   98,  106,   97,
      126,  101,  107,  109,  370,  100,  103,  108,  101,  134,
      103,  103,  105,  110,  129,  108,  110,  105,  123,  107,
      114,  114,  114,  114,  109,  126,  107,  127,  115,  109,
      115,  115,  115,  115,  134,  326,  110,  129,  133,  326,
      115,  127,  110,  116,  116,  116,  116,  117,  117,  117,
      117,  128,  133,  116,  118,  118,  118,  118,  125,  125,

      125,  125,  130,  131,  132,  132,  115,  136,  137,  130,
      138,  132,  128,  140,  143,  131,  138,  128,  136,  116,
      139,  143,  139,  131,  142,  139,  141,  140,  144,  137,
      125,  145,  141,  146,  137,  139,  147,  151,  152,  139,
      148,  149,  139,  151,  150,  142,  139,  153,  139,  139,
      142,  148,  145,  144,  155,  149,  146,  145,  150,  152,
      147,  154,  157,  147,  152,  158,  366,  154,  153,  159,
      157,  158,  160,  153,  157,  155,  161,  160,  162,  163,
      155,  161,  157,  159,  162,  163,  164,  165,  166,  168,
      365,  171,  173,  174,  177,  178,  178,  164,  175,  175,

      175,  175,  177,  182,  165,  171,  173,  187,  175,  166,
      168,  165,  181,  187,  166,  168,  185,  184,  174,  176,
      176,  176,  176,  185,  186,  174,  189,  181,  182,  176,
      180,  180,  180,  180,  175,  184,  188,  190,  194,  192,
      193,  193,  190,  195,  197,  186,  196,  197,  364,  198,
      186,  189,  202,  188,  195,  176,  192,  201,  204,  194,
      188,  203,  180,  192,  194,  205,  196,  198,  206,  201,
      208,  205,  196,  202,  209,  203,  210,  201,  202,  209,
      210,  211,  212,  204,  215,  214,  216,  217,  212,  211,
      215,  208,  214,  206,  220,  218,  208,  219,  221,  224,

      222,  210,  220,  226,  223,  224,  210,  223,  217,  226,
      227,  216,  218,  217,  219,  221,  228,  229,  231,  218,
      234,  219,  221,  222,  240,  229,  241,  230,  230,  230,
      230,  227,  240,  239,  242,  244,  227,  230,  228,  251,
      241,  245,  228,  231,  234,  239,  257,  234,  247,  245,
      248,  249,  250,  239,  242,  253,  255,  254,  244,  252,
      242,  258,  251,  230,  362,  247,  250,  248,  256,  253,
      254,  257,  247,  249,  248,  260,  252,  249,  255,  263,
      256,  258,  255,  252,  262,  260,  264,  258,  256,  265,
      262,  266,  274,  267,  268,  275,  277,  274,  278,  276,

      279,  277,  263,  266,  282,  360,  279,  281,  283,  264,
      265,  266,  268,  276,  283,  265,  267,  284,  275,  278,
      285,  281,  286,  286,  278,  282,  287,  285,  288,  290,
      282,  284,  291,  292,  294,  293,  318,  295,  318,  288,
      297,  299,  296,  305,  287,  304,  297,  309,  311,  299,
      290,  304,  306,  291,  310,  290,  292,  293,  291,  294,
      312,  293,  295,  296,  305,  316,  319,  324,  296,  305,
      317,  311,  309,  306,  321,  322,  330,  316,  306,  310,
      320,  312,  317,  325,  330,  316,  312,  319,  324,  331,
      317,  320,  319,  324,  335,  332,  336,  321,  322,  337,

      335,  338,  339,  340,  325,  345,  359,  336,  341,  325,
      337,  348,  331,  332,  342,  346,  342,  350,  348,  361,
      349,  338,  368,  339,  340,  355,  345,  338,  339,  340,
      341,  345,  349,  346,  341,  363,  355,  350,  367,  371,
      349,  358,  361,  350,  369,  368,  369,  363,  378,  357,
      369,  372,  356,  372,  378,  363,  379,  372,  379,  367,
      371,  354,  353,  352,  367,  371,  383,  351,  383,  383,
      383,  383,  383,  383,  384,  384,  385,  347,  385,  385,
      385,  385,  385,  385,  386,  386,  386,  386,  387,  387,
      387,  388,  388,  389,  389,  390,  390,  391,  334,  391,

      391,  391,  392,  392,  392,  392,  393,  333,  393,  393,
      393,  393,  393,  393,  394,  329,  394,  394,  394,  394,
      394,  394,  328,  327,  323,  315,  314,  313,  308,  307,
      302,  301,  300,  298,  289,  280,  273,  272,  271,  270,
      269,  261,  259,  246,  243,  238,  237,  236,  235,  233,
      232,  225,  213,  207,  200,  199,  191,  183,  172,  170,
      169,  167,  156,  135,  124,  122,  113,  111,   96,   89,
       76,   68,   64,   50,   47,   30,   14,   11,    3,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,

      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382,
      382,  382,  382,  382,  382,  382,  382,  382,  382,  382
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\Proyecto1.l"
#define INITIAL 0
#line 2 ".\\Proyecto1.l"

#include <stdio.h>


#line 726 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 47 ".\\Proyecto1.l"


#line 880 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 383 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 980 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 50 ".\\Proyecto1.l"
case 2:
#line 51 ".\\Proyecto1.l"
case 3:
#line 52 ".\\Proyecto1.l"
case 4:
#line 53 ".\\Proyecto1.l"
case 5:
#line 54 ".\\Proyecto1.l"
case 6:
#line 55 ".\\Proyecto1.l"
case 7:
#line 56 ".\\Proyecto1.l"
case 8:
#line 57 ".\\Proyecto1.l"
case 9:
#line 58 ".\\Proyecto1.l"
case 10:
#line 59 ".\\Proyecto1.l"
case 11:
#line 60 ".\\Proyecto1.l"
case 12:
#line 61 ".\\Proyecto1.l"
case 13:
#line 62 ".\\Proyecto1.l"
case 14:
#line 63 ".\\Proyecto1.l"
case 15:
#line 64 ".\\Proyecto1.l"
case 16:
#line 65 ".\\Proyecto1.l"
case 17:
#line 66 ".\\Proyecto1.l"
case 18:
#line 67 ".\\Proyecto1.l"
case 19:
#line 68 ".\\Proyecto1.l"
case 20:
#line 69 ".\\Proyecto1.l"
case 21:
#line 70 ".\\Proyecto1.l"
case 22:
#line 71 ".\\Proyecto1.l"
case 23:
#line 72 ".\\Proyecto1.l"
case 24:
#line 73 ".\\Proyecto1.l"
case 25:
#line 74 ".\\Proyecto1.l"
case 26:
#line 75 ".\\Proyecto1.l"
case 27:
#line 76 ".\\Proyecto1.l"
case 28:
#line 77 ".\\Proyecto1.l"
case 29:
#line 78 ".\\Proyecto1.l"
case 30:
#line 79 ".\\Proyecto1.l"
case 31:
#line 80 ".\\Proyecto1.l"
case 32:
#line 81 ".\\Proyecto1.l"
case 33:
#line 82 ".\\Proyecto1.l"
case 34:
#line 83 ".\\Proyecto1.l"
case 35:
#line 84 ".\\Proyecto1.l"
case 36:
#line 85 ".\\Proyecto1.l"
case 37:
#line 86 ".\\Proyecto1.l"
case 38:
#line 87 ".\\Proyecto1.l"
case 39:
#line 88 ".\\Proyecto1.l"
case 40:
#line 89 ".\\Proyecto1.l"
case 41:
#line 90 ".\\Proyecto1.l"
case 42:
#line 91 ".\\Proyecto1.l"
case 43:
#line 92 ".\\Proyecto1.l"
case 44:
#line 93 ".\\Proyecto1.l"
case 45:
#line 94 ".\\Proyecto1.l"
case 46:
#line 95 ".\\Proyecto1.l"
case 47:
#line 96 ".\\Proyecto1.l"
case 48:
#line 97 ".\\Proyecto1.l"
case 49:
#line 98 ".\\Proyecto1.l"
case 50:
#line 99 ".\\Proyecto1.l"
case 51:
#line 100 ".\\Proyecto1.l"
case 52:
#line 101 ".\\Proyecto1.l"
case 53:
#line 102 ".\\Proyecto1.l"
case 54:
#line 103 ".\\Proyecto1.l"
case 55:
#line 104 ".\\Proyecto1.l"
case 56:
#line 105 ".\\Proyecto1.l"
case 57:
#line 106 ".\\Proyecto1.l"
case 58:
#line 107 ".\\Proyecto1.l"
case 59:
#line 108 ".\\Proyecto1.l"
case 60:
#line 109 ".\\Proyecto1.l"
case 61:
#line 110 ".\\Proyecto1.l"
case 62:
#line 111 ".\\Proyecto1.l"
case 63:
#line 112 ".\\Proyecto1.l"
case 64:
#line 113 ".\\Proyecto1.l"
case 65:
#line 114 ".\\Proyecto1.l"
case 66:
YY_RULE_SETUP
#line 114 ".\\Proyecto1.l"
{printf("Reservada\n"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 116 ".\\Proyecto1.l"
{printf("igual\n"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 117 ".\\Proyecto1.l"
{printf("llave\n"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 118 ".\\Proyecto1.l"
{printf("parentesis\n"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 126 ".\\Proyecto1.l"
{printf("Op aritmetica\t\n"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 127 ".\\Proyecto1.l"
{printf("Op aritmetica\t\n"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 128 ".\\Proyecto1.l"
{printf("Op aritmetica\t\n"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 129 ".\\Proyecto1.l"
{printf("Op aritmetica\t\n"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 130 ".\\Proyecto1.l"
{printf("Op aritmetica\t\n"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 131 ".\\Proyecto1.l"
{printf("Op aritmetica\t\n"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 133 ".\\Proyecto1.l"
{printf("op logica\t\n"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 134 ".\\Proyecto1.l"
{printf("op logica\t\n"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 136 ".\\Proyecto1.l"
{printf("fin_instruccion\t\n"); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 138 ".\\Proyecto1.l"
{printf("booleano\t\n"); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 140 ".\\Proyecto1.l"
{printf("entero\t\n"); } 
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 141 ".\\Proyecto1.l"
{printf("entero\t\n"); } 
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 142 ".\\Proyecto1.l"
{printf("entero\t\n"); } 
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 143 ".\\Proyecto1.l"
{printf("entero\t\n"); } 
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 145 ".\\Proyecto1.l"
{printf("decimal\t\n"); } 
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 146 ".\\Proyecto1.l"
{printf("decimal\t\n"); } 
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 148 ".\\Proyecto1.l"
{printf("cadena\t\n"); } 
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 149 ".\\Proyecto1.l"
{printf("cadena\t\n"); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 151 ".\\Proyecto1.l"
{printf("variable\t\n"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 153 ".\\Proyecto1.l"
{printf("constante\t\n"); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 154 ".\\Proyecto1.l"
{printf("constante\t\n"); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 162 ".\\Proyecto1.l"
;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 163 ".\\Proyecto1.l"
{printf("No reconocido\t\n"); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 166 ".\\Proyecto1.l"
ECHO;
	YY_BREAK
#line 1233 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 383 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 383 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 382);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 166 ".\\Proyecto1.l"


int yywrap()
{
    return 1;
}
int main(void)
{
    yylex();
    return 0;
}
