/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
static yyconst short int yy_accept[370] =
    {   0,
        0,    0,  100,   98,   97,   97,   82,   98,   98,   76,
       98,   98,   65,   73,   71,   68,   72,   69,   74,   84,
       84,   70,   67,   98,   62,   98,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   98,   64,   64,
        0,   92,   80,    0,   75,    0,    0,   84,   84,   88,
       88,   86,    0,    0,    0,    0,   84,    0,   63,    2,
       96,   96,   96,   96,    5,    0,   96,   96,   96,   96,
       96,   96,   16,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   93,   96,   96,   96,   96,

       96,   96,   78,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   66,   81,   91,   92,
       90,    0,    0,   88,    0,   89,   87,   85,    0,   96,
       77,   96,    0,    0,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   15,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   30,   96,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   44,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   56,   96,   58,   59,   96,
       79,   96,    0,    0,    0,   96,   96,   96,    0,   96,
       96,    8,   96,   96,   96,   96,   96,   96,   17,   94,

       96,   96,   96,   96,   96,   96,   25,   26,   96,   96,
       96,   96,   96,   96,   34,   96,   96,   96,   96,   96,
       42,   96,   96,   96,   96,   96,   96,   96,   96,   96,
       96,   96,   83,   96,   96,   96,    0,    1,   96,    4,
        6,   96,    9,   10,   11,   96,   96,   96,   96,   18,
       96,   96,   22,   96,   96,   96,   28,   96,   96,   96,
       96,   96,   96,   96,   96,   41,   96,   45,   96,   96,
       96,   96,   96,   96,   96,   54,   55,   57,   60,   61,
       96,   96,   96,   96,   96,   95,   96,   20,   96,   96,
       96,   96,   96,   96,   33,   96,   96,   96,   96,   96,

       96,   96,   96,   48,   96,   51,   52,   53,   96,   96,
       96,   13,   14,   96,   96,   96,   96,   27,   29,   31,
       96,   96,   36,   96,   96,   96,   96,   46,   96,   96,
        3,    7,   12,   96,   96,   96,   24,   32,   96,   96,
       96,   96,   96,   96,   96,   49,   96,   96,   23,   96,
       96,   96,   39,   40,   43,   47,   96,   19,   21,   35,
       96,   38,   96,   96,   96,   37,   96,   50,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   36,
       52,    1,   53,    1,   54,    1,   27,   55,   29,   30,

       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   36,   56,   57,   56,    1,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    6,    1,    5,    4,    1,    1
    } ;

static yyconst short int yy_base[376] =
    {   0,
        0,    0,  815,  816,  816,  816,  816,    0,    0,  816,
      806,    0,  816,  802,   46,  816,   55,   59,  816,   65,
       71,  816,  816,  786,  787,  785,   53,   43,   65,   69,
       84,   92,   73,  757,   98,   64,  104,   57,  101,   76,
      100,  107,  102,  113,   60,   77,  120,  755,  816,  104,
      802,    0,  816,  797,  816,  149,  156,  162,  168,  172,
      177,  187,  196,  211,    0,  145,  217,  763,  816,  816,
      752,  126,  168,  157,  751,  221,  169,  204,  192,   19,
      214,  193,  750,  213,  206,  118,  222,  226,  224,  216,
      170,  211,  217,  219,   16,  749,  220,  235,  230,  232,

      234,  236,  748,  248,  239,  247,  252,  257,  251,  269,
      253,  266,  258,  271,  263,  270,  816,  816,  794,    0,
      789,  294,  309,  313,  317,  328,    0,  321,  763,  273,
      744,  290,  742,  332,  314,  305,  322,  325,  310,  316,
      312,  321,  334,  742,  319,  332,  323,  346,  327,  336,
      341,  335,  340,  352,  360,  342,  349,  358,  361,  354,
      371,  372,  359,  376,  741,  368,  363,  379,  367,  374,
      381,  383,  384,  387,  399,  740,  401,  739,  738,  396,
      737,  400,  423,  427,  746,  405,  404,  816,  442,  413,
      436,  735,  430,  421,  437,  432,  442,  423,  734,  439,

      420,  445,  438,  446,  428,  447,  733,  732,  452,  454,
      448,  456,  441,  469,  731,  470,  455,  478,  459,  464,
      730,  467,  468,  486,  484,  482,  483,  479,  489,  496,
      477,  481,  729,  491,  497,  502,  527,  816,  512,  728,
      727,  514,  726,  725,  724,  500,  507,  515,  518,  723,
      526,  513,  722,  521,  525,  531,  524,  534,  533,  536,
      532,  542,  535,  552,  548,  721,  539,  720,  543,  553,
      561,  562,  556,  563,  564,  719,  718,  717,  716,  715,
      568,  565,  554,  571,  566,  714,  569,  578,  573,  572,
      577,  575,  594,  590,  713,  580,  602,  605,  606,  608,

      610,  607,  593,  712,  596,  711,  697,  689,  595,  612,
      613,  685,  684,  622,  623,  624,  620,  682,  681,  680,
      615,  616,  609,  621,  625,  640,  641,  679,  647,  648,
      678,  677,  676,  636,  642,  649,  673,  671,  635,  643,
      644,  650,  655,  658,  660,  651,  666,  657,  670,  659,
      668,  674,  667,  547,  385,  366,  672,  256,  209,  174,
      669,  132,  675,  683,  687,  106,  686,   74,  816,  739,
      742,  747,  751,  755,  758
    } ;

static yyconst short int yy_def[376] =
    {   0,
      369,    1,  369,  369,  369,  369,  369,  370,  371,  369,
      369,  372,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  369,  369,  369,
      370,  374,  369,  372,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  375,  369,  369,  369,  369,  369,
      373,  373,  373,  373,  373,  369,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  369,  369,  370,  374,
      372,  369,  369,  369,  369,  369,  375,  369,  369,  373,
      373,  373,  369,  369,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  369,  369,  369,  373,  373,  369,  369,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  369,  369,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,    0,  369,
      369,  369,  369,  369,  369
    } ;

static yyconst short int yy_nxt[874] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,    4,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   34,   34,   36,   34,   37,
       38,   39,   34,   40,   41,   42,   43,   44,   45,   46,
       47,   48,    4,   34,   28,   49,   50,   56,  141,   56,
       57,  157,   58,   59,   59,   59,   56,   76,   56,   57,
       76,   58,   59,   59,   59,   60,   60,   60,   60,   61,
       72,   62,   62,   62,   63,   61,   77,   67,   67,   67,
       67,   78,   73,  114,   76,   64,   74,   75,  100,   81,

      103,   64,   79,   82,   76,   80,  106,   72,   76,   83,
       94,   76,   84,   95,   65,   76,   76,  115,   90,   66,
       76,   85,   86,   87,   76,   76,   91,   76,   76,   96,
      101,   88,   92,   89,  102,   76,   97,   98,   93,  113,
      109,  111,   99,   76,  104,  107,  112,  105,  108,   76,
      110,   76,   76,   76,  116,   76,  117,   76,   76,  147,
      118,  128,  128,  122,   76,  123,  123,  123,  123,   76,
      130,   76,   60,   60,   60,   60,   61,   76,   62,   62,
       62,   63,   61,   76,   67,   67,   67,   67,   60,   60,
       60,   60,   64,  124,  124,  124,  124,  131,   64,  135,

      132,   61,   64,   62,   62,   62,   63,   64,   76,  153,
       61,   65,   63,   63,   63,   63,   66,   64,  139,   76,
       76,   76,  125,  144,  125,   76,   64,  126,  126,  126,
      126,   61,  140,   67,   67,   67,   67,  133,  134,  134,
      134,  136,  142,   76,   76,  143,  145,   64,  137,  138,
      146,  148,  149,  152,  154,   76,  155,   76,  150,  156,
       76,  158,   76,  159,   76,   76,  168,   76,   76,  151,
       76,   76,  164,   76,  162,   76,  163,   76,  171,  160,
      161,   76,  166,   76,  165,   76,   76,   76,  167,  169,
       76,  172,  170,  168,  173,  174,  178,  177,   76,   76,

      182,  179,   76,   76,   76,  180,  181,   76,   76,   76,
      183,  183,  183,  183,   76,  175,  187,   76,  186,  176,
       76,   76,   76,  184,   76,  123,  123,  123,  123,  124,
      124,  124,  124,  126,  126,  126,  126,  128,  128,   64,
      190,   76,  191,   64,  126,  126,  126,  126,  189,  189,
      189,  189,  192,  193,  194,  195,   76,  196,  197,  199,
      198,   76,  200,   76,  207,   76,  211,   76,  201,  214,
       76,  209,   76,   76,   76,  202,   76,  203,   76,  210,
      204,  208,  212,   76,  188,   76,   76,   76,  213,  215,
      205,   76,   76,   76,  206,  216,  214,   76,  217,  218,

       76,  219,  220,   76,  221,   76,  222,  223,  225,   76,
       76,   76,   76,  227,   76,  224,  226,   76,   76,   76,
      228,  232,   76,   76,  231,   76,  229,   76,  230,  233,
       76,  234,   76,  235,   76,   76,   76,  236,   76,  183,
      183,  183,  183,  237,  237,  237,  237,   76,  239,  241,
       76,   76,   76,   64,  240,   76,   76,   64,  189,  189,
      189,  189,  242,  243,   76,  244,  246,  245,  247,  248,
      250,   76,   76,  249,   76,  251,  254,  253,  252,   76,
      255,   76,  258,   76,  233,  257,  259,   76,   76,   76,
       76,  256,   76,   76,  188,  260,   76,   76,   76,   76,

      261,  262,  265,   76,  263,   76,   76,   76,  264,  266,
       76,  267,  269,  268,  270,   76,  271,  272,   76,   76,
       76,   76,  273,  274,  275,  276,  277,  279,   76,   76,
       76,  280,   76,   76,   76,   76,  278,   76,  281,  283,
       76,  282,   76,  237,  237,  237,  237,   76,   76,  286,
      284,   76,  285,   76,  287,  289,  288,   64,   76,  290,
      291,  292,  293,   76,   76,   76,   76,  294,  282,   76,
      296,  297,   76,  295,  298,   76,   76,   76,  299,  300,
      301,  303,   76,   76,   76,   76,   76,   76,  302,  304,
       76,  307,  305,   76,   76,  306,  309,  308,   76,   76,

      311,  312,  310,   76,   76,   76,  314,   76,  315,  317,
      322,  313,   76,   76,   76,   76,   76,   76,  316,   76,
       76,  318,   76,   76,   76,  319,   76,  320,   76,   76,
      321,   76,  323,  324,  326,  325,  327,  328,  329,  330,
      331,   76,  332,  333,   76,   76,   76,   76,  334,  335,
      337,  341,  336,   76,  338,  339,   76,   76,   76,   76,
       76,   76,  340,   76,   76,  342,   76,   76,  343,  344,
      348,   76,   76,   76,   76,   76,   76,  345,  346,  347,
      350,  353,  349,  351,  352,  354,   76,   76,  355,  356,
      359,   76,   76,   76,   76,   76,  358,  364,   76,   76,

       76,   76,   76,  360,  357,  362,   76,  361,   76,   76,
       76,   76,  363,  366,  365,  367,  368,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   51,
       76,   51,   51,   51,   51,   52,   52,   54,   76,   54,
       54,   54,   54,   71,   71,   71,   71,  120,  120,  120,
      127,  127,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,  238,   76,   76,
       76,   76,   76,   76,  188,   76,  185,  121,  119,   76,

       76,   76,   76,   76,  129,  121,  119,  117,   76,   70,
       69,   68,   55,   53,  369,    3,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369
    } ;

static yyconst short int yy_chk[874] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   15,   80,   15,
       15,   95,   15,   15,   15,   15,   17,   95,   17,   17,
       80,   17,   17,   17,   17,   18,   18,   18,   18,   20,
       27,   20,   20,   20,   20,   21,   28,   21,   21,   21,
       21,   29,   27,   45,   28,   20,   27,   27,   36,   30,

       38,   21,   29,   30,   27,   29,   40,   27,   38,   30,
       33,   45,   31,   33,   20,   36,   29,   46,   32,   20,
       30,   31,   31,   31,   33,  368,   32,   40,   46,   35,
       37,   31,   32,   31,   37,   31,   35,   35,   32,   44,
       42,   43,   35,   32,   39,   41,   43,   39,   41,   35,
       42,   41,   39,   43,   47,   37,   50,  366,   42,   86,
       50,   66,   66,   56,   44,   56,   56,   56,   56,   86,
       72,   47,   57,   57,   57,   57,   58,   72,   58,   58,
       58,   58,   59,  362,   59,   59,   59,   59,   60,   60,
       60,   60,   58,   61,   61,   61,   61,   73,   59,   77,

       74,   62,   60,   62,   62,   62,   62,   61,   74,   91,
       63,   58,   63,   63,   63,   63,   58,   62,   79,   73,
       77,   91,   64,   82,   64,  360,   63,   64,   64,   64,
       64,   67,   79,   67,   67,   67,   67,   76,   76,   76,
       76,   78,   81,   79,   82,   81,   84,   67,   78,   78,
       85,   87,   88,   90,   92,   78,   93,   85,   89,   94,
      359,   97,   92,   98,   84,   81,  105,   90,   93,   89,
       94,   97,  101,   87,   99,   89,  100,   88,  107,   98,
       98,   99,  104,  100,  102,  101,   98,  102,  104,  106,
      105,  108,  106,  105,  109,  110,  112,  111,  106,  104,

      116,  113,  109,  107,  111,  114,  115,  358,  108,  113,
      122,  122,  122,  122,  115,  110,  132,  112,  130,  110,
      110,  116,  114,  123,  130,  123,  123,  123,  123,  124,
      124,  124,  124,  125,  125,  125,  125,  128,  128,  123,
      135,  132,  136,  124,  126,  126,  126,  126,  134,  134,
      134,  134,  137,  138,  139,  140,  136,  141,  142,  145,
      143,  139,  146,  141,  149,  135,  153,  140,  147,  156,
      145,  151,  142,  137,  147,  148,  138,  148,  149,  152,
      148,  150,  154,  146,  134,  143,  152,  150,  155,  157,
      148,  153,  151,  156,  148,  158,  156,  148,  159,  160,

      157,  161,  162,  154,  163,  160,  164,  166,  167,  158,
      163,  155,  159,  169,  167,  166,  168,  356,  169,  166,
      170,  174,  161,  162,  173,  170,  171,  164,  172,  175,
      168,  177,  171,  180,  172,  173,  355,  182,  174,  183,
      183,  183,  183,  184,  184,  184,  184,  180,  186,  190,
      175,  182,  177,  183,  187,  187,  186,  184,  189,  189,
      189,  189,  191,  193,  190,  194,  196,  195,  197,  198,
      201,  201,  194,  200,  198,  202,  205,  204,  203,  205,
      206,  193,  212,  196,  210,  211,  213,  191,  195,  203,
      200,  209,  213,  197,  189,  214,  202,  204,  206,  211,

      216,  217,  219,  209,  218,  210,  217,  212,  218,  220,
      219,  222,  224,  223,  225,  220,  226,  227,  222,  223,
      214,  216,  228,  229,  230,  231,  232,  235,  231,  218,
      228,  236,  232,  226,  227,  225,  234,  224,  239,  246,
      229,  242,  234,  237,  237,  237,  237,  230,  235,  249,
      247,  246,  248,  236,  251,  254,  252,  237,  247,  255,
      256,  257,  258,  239,  252,  242,  248,  259,  242,  249,
      261,  262,  254,  260,  263,  257,  255,  251,  264,  265,
      267,  270,  256,  261,  259,  258,  263,  260,  269,  271,
      267,  274,  272,  262,  269,  273,  281,  275,  354,  265,

      283,  284,  282,  264,  270,  283,  287,  273,  288,  290,
      296,  285,  271,  272,  274,  275,  282,  285,  289,  281,
      287,  291,  284,  290,  289,  292,  292,  293,  291,  288,
      294,  296,  297,  298,  300,  299,  301,  302,  303,  305,
      309,  294,  310,  311,  303,  293,  309,  305,  314,  315,
      317,  324,  316,  297,  321,  322,  298,  299,  302,  300,
      323,  301,  323,  310,  311,  325,  321,  322,  326,  327,
      335,  317,  324,  314,  315,  316,  325,  329,  330,  334,
      339,  342,  336,  340,  341,  343,  339,  334,  344,  345,
      348,  326,  327,  335,  340,  341,  347,  361,  329,  330,

      336,  342,  346,  350,  346,  352,  343,  351,  348,  344,
      350,  345,  357,  364,  363,  365,  367,  347,  353,  351,
      361,  349,  338,  357,  337,  352,  363,  333,  332,  331,
      328,  320,  319,  318,  364,  313,  312,  367,  365,  370,
      308,  370,  370,  370,  370,  371,  371,  372,  307,  372,
      372,  372,  372,  373,  373,  373,  373,  374,  374,  374,
      375,  375,  306,  304,  295,  286,  280,  279,  278,  277,
      276,  268,  266,  253,  250,  245,  244,  243,  241,  240,
      233,  221,  215,  208,  207,  199,  192,  185,  181,  179,
      178,  176,  165,  144,  133,  131,  129,  121,  119,  103,

       96,   83,   75,   71,   68,   54,   51,   48,   34,   26,
       25,   24,   14,   11,    3,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  369,  369,  369,  369,
      369,  369,  369
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\Proyecto1.l"
#define INITIAL 0
#line 2 ".\\Proyecto1.l"

#include <stdio.h>


#line 682 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 47 ".\\Proyecto1.l"


#line 836 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 370 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 816 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 50 ".\\Proyecto1.l"
case 2:
YY_RULE_SETUP
#line 50 ".\\Proyecto1.l"
{printf("Etiqueta php\n"); }
	YY_BREAK
case 3:
#line 53 ".\\Proyecto1.l"
case 4:
#line 54 ".\\Proyecto1.l"
case 5:
#line 55 ".\\Proyecto1.l"
case 6:
#line 56 ".\\Proyecto1.l"
case 7:
#line 57 ".\\Proyecto1.l"
case 8:
#line 58 ".\\Proyecto1.l"
case 9:
#line 59 ".\\Proyecto1.l"
case 10:
#line 60 ".\\Proyecto1.l"
case 11:
#line 61 ".\\Proyecto1.l"
case 12:
#line 62 ".\\Proyecto1.l"
case 13:
#line 63 ".\\Proyecto1.l"
case 14:
#line 64 ".\\Proyecto1.l"
case 15:
#line 65 ".\\Proyecto1.l"
case 16:
#line 66 ".\\Proyecto1.l"
case 17:
#line 67 ".\\Proyecto1.l"
case 18:
#line 68 ".\\Proyecto1.l"
case 19:
#line 69 ".\\Proyecto1.l"
case 20:
#line 70 ".\\Proyecto1.l"
case 21:
#line 71 ".\\Proyecto1.l"
case 22:
#line 72 ".\\Proyecto1.l"
case 23:
#line 73 ".\\Proyecto1.l"
case 24:
#line 74 ".\\Proyecto1.l"
case 25:
#line 75 ".\\Proyecto1.l"
case 26:
#line 76 ".\\Proyecto1.l"
case 27:
#line 77 ".\\Proyecto1.l"
case 28:
#line 78 ".\\Proyecto1.l"
case 29:
#line 79 ".\\Proyecto1.l"
case 30:
#line 80 ".\\Proyecto1.l"
case 31:
#line 81 ".\\Proyecto1.l"
case 32:
#line 82 ".\\Proyecto1.l"
case 33:
#line 83 ".\\Proyecto1.l"
case 34:
#line 84 ".\\Proyecto1.l"
case 35:
#line 85 ".\\Proyecto1.l"
case 36:
#line 86 ".\\Proyecto1.l"
case 37:
#line 87 ".\\Proyecto1.l"
case 38:
#line 88 ".\\Proyecto1.l"
case 39:
#line 89 ".\\Proyecto1.l"
case 40:
#line 90 ".\\Proyecto1.l"
case 41:
#line 91 ".\\Proyecto1.l"
case 42:
#line 92 ".\\Proyecto1.l"
case 43:
#line 93 ".\\Proyecto1.l"
case 44:
#line 94 ".\\Proyecto1.l"
case 45:
#line 95 ".\\Proyecto1.l"
case 46:
#line 96 ".\\Proyecto1.l"
case 47:
#line 97 ".\\Proyecto1.l"
case 48:
#line 98 ".\\Proyecto1.l"
case 49:
#line 99 ".\\Proyecto1.l"
case 50:
#line 100 ".\\Proyecto1.l"
case 51:
#line 101 ".\\Proyecto1.l"
case 52:
#line 102 ".\\Proyecto1.l"
case 53:
#line 103 ".\\Proyecto1.l"
case 54:
#line 104 ".\\Proyecto1.l"
case 55:
#line 105 ".\\Proyecto1.l"
case 56:
#line 106 ".\\Proyecto1.l"
case 57:
#line 107 ".\\Proyecto1.l"
case 58:
#line 108 ".\\Proyecto1.l"
case 59:
#line 109 ".\\Proyecto1.l"
case 60:
#line 110 ".\\Proyecto1.l"
case 61:
YY_RULE_SETUP
#line 110 ".\\Proyecto1.l"
{printf("Reservada\n"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 112 ".\\Proyecto1.l"
{printf("igual\n"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 113 ".\\Proyecto1.l"
{printf("igualdad\n"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 114 ".\\Proyecto1.l"
{printf("llave\n"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 115 ".\\Proyecto1.l"
{printf("parentesis\n"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 116 ".\\Proyecto1.l"
{printf("corchete\n"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 117 ".\\Proyecto1.l"
{printf("fin_instruccion\n"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 118 ".\\Proyecto1.l"
{printf("coma\n"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 119 ".\\Proyecto1.l"
{printf("punto\n"); } 
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 120 ".\\Proyecto1.l"
{printf("dos puntos\n"); }
	YY_BREAK
case 71:
#line 124 ".\\Proyecto1.l"
case 72:
#line 125 ".\\Proyecto1.l"
case 73:
#line 126 ".\\Proyecto1.l"
case 74:
#line 127 ".\\Proyecto1.l"
case 75:
#line 128 ".\\Proyecto1.l"
case 76:
YY_RULE_SETUP
#line 128 ".\\Proyecto1.l"
{printf("Op aritmetico\n"); }
	YY_BREAK
case 77:
#line 131 ".\\Proyecto1.l"
case 78:
#line 132 ".\\Proyecto1.l"
case 79:
#line 133 ".\\Proyecto1.l"
case 80:
#line 134 ".\\Proyecto1.l"
case 81:
#line 135 ".\\Proyecto1.l"
case 82:
YY_RULE_SETUP
#line 135 ".\\Proyecto1.l"
{printf("op logica\n"); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 137 ".\\Proyecto1.l"
{printf("t bool\n"); }
	YY_BREAK
case 84:
#line 140 ".\\Proyecto1.l"
case 85:
#line 141 ".\\Proyecto1.l"
case 86:
#line 142 ".\\Proyecto1.l"
case 87:
YY_RULE_SETUP
#line 142 ".\\Proyecto1.l"
{printf("t entero\n"); } 
	YY_BREAK
case 88:
#line 145 ".\\Proyecto1.l"
case 89:
YY_RULE_SETUP
#line 145 ".\\Proyecto1.l"
{printf("t decimal\n"); } 
	YY_BREAK
case 90:
#line 148 ".\\Proyecto1.l"
case 91:
YY_RULE_SETUP
#line 148 ".\\Proyecto1.l"
{printf("cadena\n"); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 150 ".\\Proyecto1.l"
{printf("variable\n"); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 152 ".\\Proyecto1.l"
{printf("estruct if\n"); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 153 ".\\Proyecto1.l"
{printf("estruct else\n"); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 154 ".\\Proyecto1.l"
{printf("estruct elseif\n"); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 156 ".\\Proyecto1.l"
{printf("constante\n"); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 159 ".\\Proyecto1.l"
;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 160 ".\\Proyecto1.l"
{printf("No reconocido\t\n"); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 163 ".\\Proyecto1.l"
ECHO;
	YY_BREAK
#line 1192 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 370 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 370 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 369);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 163 ".\\Proyecto1.l"


int yywrap()
{
    return 1;
}
int main(void)
{
    yylex();
    return 0;
}
