/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 114
#define YY_END_OF_BUFFER 115
static yyconst short int yy_accept[473] =
    {   0,
        0,    0,  115,  113,  112,  112,   73,  113,  113,   67,
      113,  113,   55,   64,   62,   59,   63,   60,   65,   75,
       75,   61,   58,   57,   52,   57,  113,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  113,   54,
       54,    0,   97,   97,   97,   97,   97,   97,   97,   71,
        0,   66,    0,    0,   75,   75,   79,   79,   77,    0,
        0,    0,    0,   75,    0,   53,    2,  111,  111,  111,
      111,    5,    0,  111,  111,  111,  111,  111,  111,  102,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,

      111,  111,   98,  111,  111,  111,  111,  111,  111,   69,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,   56,   72,   82,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   81,
        0,    0,   79,    0,   80,   78,   76,    0,  111,   68,
      111,    0,    0,  111,  111,  111,  111,  111,  111,  111,
      111,  111,   12,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  103,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,   37,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,   47,  111,   49,   50,  111,   70,

      111,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,    0,    0,    0,  111,  111,  111,    0,
      111,  111,  107,  111,  111,  111,  111,  111,  111,   13,
       99,  111,  111,  111,  111,  111,  111,   21,   22,  111,
      111,  111,  111,  111,  111,   28,  111,  111,  111,  111,
      111,   35,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,   74,  111,  111,  111,   97,   97,   97,
       90,   97,   85,   97,   97,   97,   97,   95,   96,   97,
       97,    0,    1,  111,    4,  105,  111,    7,    8,    9,
      111,  111,  111,  111,   14,  111,  111,   18,  111,  111,

      111,   24,  111,  111,  111,  111,  111,  111,  111,  111,
       34,  111,   38,  111,  111,  111,  111,  111,  111,  111,
       45,   46,   48,  101,   51,   97,   97,   97,   97,   86,
       97,   97,   97,   97,   97,  111,  111,  111,  111,  111,
      100,  111,   16,  111,  111,  111,  111,  111,  111,   27,
      111,  111,  111,  111,  111,  111,  111,  111,   41,  111,
      110,   44,  106,   97,   97,   97,   87,   97,   97,   97,
       97,   97,  111,  111,  111,   10,   11,  111,  111,  111,
      111,   23,   25,  104,  111,  111,  108,  111,  111,  111,
      111,   39,  111,  111,   83,   97,   91,   97,   84,   97,

       97,   97,    3,    6,  109,  111,  111,  111,   20,   26,
      111,  111,  111,  111,  111,  111,  111,   42,   97,   88,
       89,   97,   97,  111,  111,   19,  111,  111,  111,   32,
       33,   36,   40,  111,   97,   97,   97,   15,   17,   29,
      111,   31,  111,   97,   97,   97,  111,  111,   97,   97,
       97,   30,  111,   97,   97,   92,   43,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   93,   97,   97,
       94,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   36,
       52,    1,   53,    1,   54,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   36,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,   74,   75,   76,   50,
       51,   36,   77,   78,   77,    1,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,

       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36
    } ;

static yyconst int yy_meta[79] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    6,    1,    5,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1
    } ;

static yyconst short int yy_base[479] =
    {   0,
        0,    0, 1219, 1220, 1220, 1220, 1220,    0,   46, 1220,
     1210,    0, 1220, 1206,   69, 1220,   78,   85, 1220,   92,
       99, 1220, 1220, 1190, 1191, 1220, 1189,   93,   76,   98,
      121,  161,  140,  103, 1161,  165,   91,  188,   88,  177,
       54,  189,  168,  204,   72,  136,  155,   94, 1159, 1220,
      108, 1206,    0, 1172, 1163,  228, 1137, 1134, 1144, 1220,
     1196, 1220,  159,  235,  249,  264,  269,  273,  294,  300,
      321,    0,  117,  327,  164, 1220, 1220, 1152,  249,  164,
      206, 1151,  331,  244,  291,  325,  315,  339,  275, 1150,
      264,  309,  255,  327,  335,  337,  332,  336,  321,  354,

      357,  349, 1149,  360,  378,  359,  368,  366,  365, 1148,
      392,  387,  402,  401,  211,  390,  411,  374,  405,  415,
      417,  421,  418, 1220, 1220, 1194,    0, 1157, 1151, 1155,
     1155, 1159, 1162, 1151, 1160, 1159, 1128, 1115, 1118, 1177,
      464,  476,  470,  480,  485,    0,  165,   60,  460, 1133,
      482, 1131,  496,  484,  479,  488,  489,  476,  486,  478,
      504,  500, 1131,  491,  514,  508,  533,  512,  515,  527,
      531,  535,  540,  543,  542,  556,  537,  563,  558,  575,
      580,  567,  583, 1130,  577,  570,  585,  574,  586,  584,
      595,  604,  611,  618, 1129,  623, 1128, 1127,  613, 1126,

      615, 1149, 1134, 1134, 1126, 1135, 1126, 1126, 1127,  330,
      303, 1100, 1114,  666,  670,  405,  627,  427, 1220,  674,
      644,  668, 1115,  666,  654,  672,  667,  680,  662, 1114,
      670,  471,  682,  669,  270,  663,  704, 1113, 1112,  700,
      711,  706,  720,  703,  726, 1111,  728,  699,  730,  725,
      722, 1110,  734,  738,  761,  760,  757,  758,  753,  763,
      555,  751,  755, 1109,  756,  773,  784, 1133, 1105, 1121,
        0, 1126,    0, 1110, 1108, 1106, 1108,    0,    0, 1085,
     1072,  820, 1220,  791, 1076, 1075,  789, 1073, 1072, 1071,
      782,  779,  792,  801, 1068,  806,  803, 1061,  813,  817,

      826,  816,  830,  825,  833,  823,  834,  843,  839,  841,
     1059,  848, 1058,  850,  868,  870,  872,  866,  878,  874,
     1056, 1055, 1053, 1052, 1050, 1062, 1053, 1061, 1045,    0,
     1056, 1036, 1031,  992,  987,  880,  876,  864,  888,  869,
      997,  891,  903,  893,  906,  901,  607,  915,  907,  993,
      920,  926,  931,  922,  934,  938,  932,  924,  959,  943,
      953,  949,  917,  923,  937,  923,    0,  905,  869,  871,
      846,  833,  946,  950,  951,  820,  818,  969,  973,  965,
      968,  815,  747,  742,  964,  966,  139,  977,  971,  978,
      986,  731,  982,  995,    0,  716,    0,  718,    0,  722,

      688,  686,  698,  696,  693,  988, 1008, 1010,  691,  665,
      996, 1005, 1009, 1019, 1022, 1024, 1026,  456,  662,    0,
        0,  642,  633, 1033, 1018,  624, 1023, 1042, 1054,  621,
      617,  614,  612, 1047,  620,  593,  589,  568,  566,  528,
     1060,  522, 1051,  516,  458,  448, 1067, 1064,  431,  399,
      407,  385, 1070,  370,  349,    0,  317,  256,  231,  248,
      183,  215,  175,  139,  117,  142,   73,    0,   32,   11,
        0, 1220, 1129, 1132, 1137, 1141, 1145, 1148
    } ;

static yyconst short int yy_def[479] =
    {   0,
      472,    1,  472,  472,  472,  472,  472,  473,  474,  472,
      472,  475,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  472,  472,
      472,  473,  477,  477,  477,  477,  477,  477,  477,  472,
      475,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  478,  472,  472,  472,  472,  472,  476,  476,  476,
      476,  476,  472,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  472,  472,  473,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  475,
      472,  472,  472,  472,  472,  478,  472,  472,  476,  476,
      476,  472,  472,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  472,  472,  472,  476,  476,  472,  472,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,  472,  472,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,

      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  477,  477,  477,  477,  477,
      477,  477,  477,  477,  477,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  477,  477,  477,  477,  477,  477,  477,
      477,  477,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  477,  477,  477,  477,  477,  477,

      477,  477,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  476,  476,  476,  476,  477,  477,
      477,  477,  477,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  477,  477,  477,  476,  476,  476,
      476,  476,  476,  477,  477,  477,  476,  476,  477,  477,
      477,  476,  476,  477,  477,  477,  476,  477,  477,  477,
      477,  477,  477,  477,  477,  477,  477,  477,  477,  477,
      477,    0,  472,  472,  472,  472,  472,  472
    } ;

static yyconst short int yy_nxt[1299] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   35,   35,   37,   35,   38,
       39,   40,   35,   41,   42,   43,   44,   45,   46,   47,
       48,   49,    4,   35,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   35,   37,   35,   38,   39,   40,   35,
       41,   42,   43,   44,   45,   46,   50,   51,   54,   55,
       63,  471,   63,   64,  113,   65,   66,   66,   66,   63,
      470,   63,   64,  216,   65,   66,   66,   66,  120,   56,

       57,   67,   67,   67,   67,   83,   68,   58,   69,   69,
       69,   70,  113,   68,   59,   74,   74,   74,   74,   84,
       79,  216,   71,   83,   85,  107,  120,   83,  123,   71,
      469,  110,   80,  147,  147,   86,   81,   82,   87,   83,
      101,   72,   83,  102,   83,   83,   84,   73,   79,   83,
       71,   88,   85,  107,   83,   89,  123,   71,  110,   80,
      124,   90,   86,   81,   82,   87,   97,  101,  468,  121,
      102,  467,   83,  141,   98,  142,  142,  142,  142,   88,
       99,  147,  147,   89,  466,  125,  100,   83,   90,   91,
       83,   83,  412,  150,   97,  122,  103,  121,   92,   93,

       94,  116,   98,  104,  105,  148,   83,   99,   95,  106,
       96,  117,   83,  100,  108,   83,   83,   91,  109,   83,
      111,  150,  122,  112,  103,   92,   93,   94,   83,  116,
      104,  105,  148,  465,  114,   95,  106,  115,  117,   83,
       83,  464,  108,  118,  463,  191,  109,  111,  119,  151,
      112,   67,   67,   67,   67,   83,  130,   83,  131,  132,
      133,  114,   83,   68,  115,   69,   69,   69,   70,  134,
      118,  135,  136,  191,  154,  119,  151,  462,   68,   71,
       74,   74,   74,   74,  461,   67,   67,   67,   67,  143,
      143,  143,  143,  149,   71,   83,  166,  164,   72,   71,

       83,  298,  154,   71,   73,  163,   83,   71,   68,  460,
       69,   69,   69,   70,   68,   83,   70,   70,   70,   70,
      149,   83,   71,  166,   71,  164,   83,   71,  155,  298,
       71,   71,  144,  163,  144,  156,  157,  145,  145,  145,
      145,   68,   83,   74,   74,   74,   74,  152,  153,  153,
      153,  158,   71,  165,  160,  155,  167,   71,   71,  278,
       83,  168,  156,  157,  173,  159,   83,  161,   83,  171,
      162,  169,   83,  276,  277,  172,   83,  279,   83,  158,
      165,  160,  170,   83,  167,   71,   83,   83,   83,  168,
       83,  173,  159,  174,  176,  161,  171,  175,  162,  169,

       83,  177,  172,  181,  183,   83,  178,  459,   83,  170,
       83,   83,  182,  184,  187,  458,   83,   83,  196,   83,
      174,  176,  179,  180,  175,   83,  185,  190,  177,   83,
      181,  183,  186,  192,  178,  197,   83,  193,   83,  182,
      184,   83,  187,   83,  188,  196,  283,  189,  201,  179,
      180,  199,   83,   83,  185,  190,   83,  194,  198,  186,
      192,  195,   83,  197,  200,  193,   83,  456,   83,   83,
      455,  188,   83,  283,  189,  454,  201,  285,   83,  199,
      214,  214,  214,  214,  194,  198,  143,  143,  143,  143,
      215,  200,  142,  142,  142,  142,  145,  145,  145,  145,

       71,  145,  145,  145,  145,  217,   71,   83,  218,  434,
      221,   83,  220,  220,  220,  220,  222,  224,  223,  451,
      225,  295,   83,  227,  450,  226,  229,   83,   71,   83,
       83,  230,  217,   83,   71,   83,  218,   83,  221,   83,
       83,  228,   83,  222,  231,  224,  223,  225,  219,  238,
      227,   83,  226,  232,  229,   83,  449,  240,  230,   83,
      239,  242,  233,   83,  234,   83,   83,  235,  228,  245,
      243,  244,  231,   83,  247,  241,  238,  236,   83,   83,
      232,  237,   83,  320,   83,  240,   83,  239,   83,  242,
      233,   83,  234,   83,   83,  235,  246,  245,  243,  244,

      248,  247,  241,  249,  236,  250,   83,   83,  237,   83,
      251,  320,  252,  253,   83,  256,  254,   83,   83,   83,
      258,   83,  257,  246,  255,   83,   83,  248,   83,  260,
      249,   83,  259,  250,   83,   83,   83,   83,  251,  252,
      261,  253,  256,  254,  262,  263,   83,  258,  264,  257,
      266,  255,  267,  265,  446,   83,  260,  383,   83,  259,
      445,  444,   83,   83,   83,   83,   83,  261,   83,   83,
      284,  262,   83,  263,   83,   83,  264,  266,   83,  267,
      286,  265,  214,  214,  214,  214,  282,  282,  282,  282,
      220,  220,  220,  220,  287,   83,   71,  284,  289,  288,

       71,  291,  290,  437,  294,   83,  292,  286,  293,  297,
      436,  299,  296,   83,   83,  435,   83,   83,   83,   83,
       83,   83,  287,   83,   71,  289,  219,  288,   71,  291,
      290,   83,  294,   83,  292,  293,  297,  300,  299,  301,
      296,  264,   83,  302,   83,  307,  303,   83,  304,   83,
       83,   83,  305,  423,   83,   83,  308,   83,  306,  422,
      309,  421,   83,  420,  419,  300,  301,  311,  310,  264,
      302,   83,  307,   83,  303,  304,   83,   83,  312,   83,
      305,   83,   83,  313,  308,   83,  306,  314,  309,   83,
      315,  316,  317,   83,  311,  310,  318,  319,   83,  321,

      322,  323,   83,  324,   83,  312,   83,   83,   83,   83,
      313,   83,   83,  325,   83,  314,  337,  336,  315,  316,
      317,  338,  339,  318,   83,  319,  321,  322,  323,  340,
       83,  324,  341,   83,  342,   83,  282,  282,  282,  282,
       83,  325,   83,   83,  337,  336,  343,  344,  338,  339,
       71,  345,   83,  347,   83,  346,  340,   83,  348,  349,
      341,  351,  342,  352,   83,  354,   83,   83,   83,   83,
      350,   83,  355,  343,   83,  344,   83,   83,   71,  345,
      347,   83,  353,  346,   83,   83,  348,  349,  351,  356,
       83,  352,   83,  354,   83,  357,  358,  350,  359,   83,

      355,   83,  360,  402,  401,  361,  362,  363,  373,  353,
      375,  400,  399,  374,  377,   83,  356,   83,  376,   83,
       83,   83,  357,   83,  358,   83,  359,   83,  378,   83,
      360,   83,  361,  379,  362,  363,  373,  375,  380,   83,
      374,  377,   83,  381,   83,  382,  376,  385,  384,  398,
      386,  389,   83,  397,   83,  378,  387,   83,   83,  388,
      390,  379,  392,  396,  391,  380,   83,  395,   83,  393,
      381,   83,  382,   83,  385,   83,  384,   83,  386,  389,
      404,  405,   83,   83,  387,   83,  394,  388,  390,   83,
      392,  403,  391,  408,   83,  406,  393,   83,  409,  407,

       83,   83,   83,  410,   83,  411,  415,  413,  404,  405,
       83,  414,  417,  394,  416,   83,   83,   83,  403,   83,
       83,  408,   83,  406,   83,  418,  409,  407,   83,   83,
      410,  424,  411,   83,  415,  413,  425,   83,  414,   83,
      417,  427,  416,  426,   83,  428,   83,   83,   83,  429,
      430,  439,  431,  418,  432,  433,   83,  372,  424,   83,
       83,   83,  371,  438,  425,  370,  369,  440,  427,   83,
       83,  426,  428,   83,   83,   83,  429,   83,  430,  439,
      431,  441,  432,  433,   83,  442,  368,  443,  447,  367,
      448,  438,  453,   83,  440,  366,  365,  452,   83,  364,

      457,   83,   83,   83,   83,   83,   83,   83,  441,   83,
       83,   83,   83,  442,  443,   83,  447,  448,   83,   83,
      453,   83,   83,   83,   83,  452,   83,   83,  457,   52,
      335,   52,   52,   52,   52,   53,   53,   61,  334,   61,
       61,   61,   61,   78,   78,   78,   78,  127,  127,  127,
      146,  146,  333,  332,  331,  330,  329,  328,  327,  326,
       83,   83,   83,   83,   83,   83,   83,  281,  280,  275,
      274,  273,  272,  271,  270,  269,  268,   83,   83,   83,
       83,   83,   83,  219,   83,  140,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  202,  126,   83,

       83,   83,   83,   83,  140,  139,  138,  137,  129,  128,
      126,  124,   83,   77,   76,   75,   62,   60,  472,    3,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472

    } ;

static yyconst short int yy_chk[1299] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    9,    9,
       15,  470,   15,   15,   41,   15,   15,   15,   15,   17,
      469,   17,   17,  148,   17,   17,   17,   17,   45,    9,

        9,   18,   18,   18,   18,   41,   20,    9,   20,   20,
       20,   20,   41,   21,    9,   21,   21,   21,   21,   29,
       28,  148,   20,   45,   30,   37,   45,   29,   48,   21,
      467,   39,   28,   73,   73,   30,   28,   28,   30,   39,
       34,   20,   37,   34,   28,   48,   29,   20,   28,   30,
       20,   31,   30,   37,   34,   31,   48,   21,   39,   28,
       51,   31,   30,   28,   28,   30,   33,   34,  466,   46,
       34,  465,   31,   63,   33,   63,   63,   63,   63,   31,
       33,  147,  147,   31,  464,   51,   33,   46,   31,   32,
      387,   33,  387,   80,   33,   47,   36,   46,   32,   32,

       32,   43,   33,   36,   36,   75,   47,   33,   32,   36,
       32,   43,   32,   33,   38,   80,   36,   32,   38,   43,
       40,   80,   47,   40,   36,   32,   32,   32,   40,   43,
       36,   36,   75,  463,   42,   32,   36,   42,   43,   38,
       42,  462,   38,   44,  461,  115,   38,   40,   44,   81,
       40,   64,   64,   64,   64,   44,   56,   81,   56,   56,
       56,   42,  115,   65,   42,   65,   65,   65,   65,   56,
       44,   56,   56,  115,   84,   44,   81,  460,   66,   65,
       66,   66,   66,   66,  459,   67,   67,   67,   67,   68,
       68,   68,   68,   79,   66,   84,   93,   91,   65,   67,

       79,  235,   84,   68,   65,   89,   93,   65,   69,  458,
       69,   69,   69,   69,   70,   91,   70,   70,   70,   70,
       79,  235,   66,   93,   69,   91,   89,   67,   85,  235,
       70,   68,   71,   89,   71,   85,   85,   71,   71,   71,
       71,   74,   85,   74,   74,   74,   74,   83,   83,   83,
       83,   86,   69,   92,   87,   85,   94,   74,   70,  211,
       92,   95,   85,   85,   99,   86,   87,   88,  457,   97,
       88,   96,   99,  210,  210,   98,   86,  211,   94,   86,
       92,   87,   96,   97,   94,   74,   95,   98,   96,   95,
       88,   99,   86,  100,  102,   88,   97,  101,   88,   96,

      102,  104,   98,  106,  108,  100,  105,  455,  101,   96,
      106,  104,  107,  109,  112,  454,  109,  108,  118,  107,
      100,  102,  105,  105,  101,  118,  111,  114,  104,  105,
      106,  108,  111,  116,  105,  119,  452,  117,  112,  107,
      109,  116,  112,  111,  113,  118,  216,  113,  123,  105,
      105,  121,  114,  113,  111,  114,  119,  117,  120,  111,
      116,  117,  117,  119,  122,  117,  120,  451,  121,  123,
      450,  113,  122,  216,  113,  449,  123,  218,  218,  121,
      141,  141,  141,  141,  117,  120,  143,  143,  143,  143,
      142,  122,  142,  142,  142,  142,  144,  144,  144,  144,

      143,  145,  145,  145,  145,  149,  142,  418,  151,  418,
      154,  149,  153,  153,  153,  153,  155,  157,  156,  446,
      158,  232,  232,  160,  445,  159,  162,  158,  143,  160,
      155,  164,  149,  151,  142,  154,  151,  159,  154,  156,
      157,  161,  164,  155,  165,  157,  156,  158,  153,  168,
      160,  162,  159,  166,  162,  161,  444,  170,  164,  166,
      169,  172,  167,  168,  167,  165,  169,  167,  161,  175,
      173,  174,  165,  442,  177,  171,  168,  167,  170,  440,
      166,  167,  171,  261,  167,  170,  172,  169,  177,  172,
      167,  173,  167,  175,  174,  167,  176,  175,  173,  174,

      178,  177,  171,  179,  167,  180,  261,  176,  167,  179,
      181,  261,  182,  183,  178,  186,  185,  439,  182,  438,
      188,  186,  187,  176,  185,  188,  180,  178,  185,  190,
      179,  181,  189,  180,  183,  190,  187,  189,  181,  182,
      191,  183,  186,  185,  192,  193,  191,  188,  194,  187,
      199,  185,  201,  196,  437,  192,  190,  347,  347,  189,
      436,  435,  193,  433,  199,  432,  201,  191,  431,  194,
      217,  192,  430,  193,  196,  426,  194,  199,  217,  201,
      221,  196,  214,  214,  214,  214,  215,  215,  215,  215,
      220,  220,  220,  220,  222,  221,  214,  217,  225,  224,

      215,  227,  226,  423,  231,  225,  228,  221,  229,  234,
      422,  236,  233,  229,  236,  419,  410,  224,  227,  222,
      234,  231,  222,  226,  214,  225,  220,  224,  215,  227,
      226,  228,  231,  233,  228,  229,  234,  237,  236,  240,
      233,  241,  409,  242,  405,  248,  243,  404,  244,  403,
      248,  240,  245,  402,  244,  237,  249,  242,  247,  401,
      249,  400,  241,  398,  396,  237,  240,  251,  250,  241,
      242,  243,  248,  251,  243,  244,  250,  245,  253,  247,
      245,  249,  392,  254,  249,  253,  247,  255,  249,  254,
      256,  257,  258,  384,  251,  250,  259,  260,  383,  262,

      263,  265,  262,  266,  259,  253,  263,  265,  257,  258,
      254,  256,  255,  267,  260,  255,  287,  284,  256,  257,
      258,  291,  292,  259,  266,  260,  262,  263,  265,  293,
      292,  266,  294,  291,  296,  267,  282,  282,  282,  282,
      287,  267,  284,  293,  287,  284,  297,  299,  291,  292,
      282,  300,  294,  302,  297,  301,  293,  296,  303,  304,
      294,  306,  296,  307,  299,  309,  382,  302,  300,  377,
      305,  376,  310,  297,  306,  299,  304,  301,  282,  300,
      302,  303,  308,  301,  305,  307,  303,  304,  306,  312,
      309,  307,  310,  309,  308,  314,  315,  305,  316,  312,

      310,  314,  317,  372,  371,  318,  319,  320,  336,  308,
      338,  370,  369,  337,  340,  338,  312,  318,  339,  315,
      340,  316,  314,  317,  315,  320,  316,  337,  342,  319,
      317,  336,  318,  343,  319,  320,  336,  338,  344,  339,
      337,  340,  342,  345,  344,  346,  339,  349,  348,  368,
      351,  354,  346,  366,  343,  342,  352,  345,  349,  353,
      355,  343,  357,  365,  356,  344,  348,  364,  363,  358,
      345,  351,  346,  354,  349,  358,  348,  352,  351,  354,
      374,  375,  353,  357,  352,  355,  360,  353,  355,  356,
      357,  373,  356,  380,  360,  378,  358,  373,  381,  379,

      362,  374,  375,  385,  361,  386,  390,  388,  374,  375,
      359,  389,  393,  360,  391,  385,  380,  386,  373,  381,
      378,  380,  389,  378,  379,  394,  381,  379,  388,  390,
      385,  406,  386,  393,  390,  388,  407,  391,  389,  406,
      393,  411,  391,  408,  350,  412,  394,  411,  341,  413,
      414,  425,  415,  394,  416,  417,  412,  335,  406,  407,
      413,  408,  334,  424,  407,  333,  332,  427,  411,  425,
      414,  408,  412,  415,  427,  416,  413,  417,  414,  425,
      415,  428,  416,  417,  424,  429,  331,  434,  441,  329,
      443,  424,  448,  428,  427,  328,  327,  447,  434,  326,

      453,  325,  443,  324,  323,  429,  322,  321,  428,  313,
      311,  441,  298,  429,  434,  448,  441,  443,  447,  295,
      448,  453,  290,  289,  288,  447,  286,  285,  453,  473,
      281,  473,  473,  473,  473,  474,  474,  475,  280,  475,
      475,  475,  475,  476,  476,  476,  476,  477,  477,  477,
      478,  478,  277,  276,  275,  274,  272,  270,  269,  268,
      264,  252,  246,  239,  238,  230,  223,  213,  212,  209,
      208,  207,  206,  205,  204,  203,  202,  200,  198,  197,
      195,  184,  163,  152,  150,  140,  139,  138,  137,  136,
      135,  134,  133,  132,  131,  130,  129,  128,  126,  110,

      103,   90,   82,   78,   61,   59,   58,   57,   55,   54,
       52,   49,   35,   27,   25,   24,   14,   11,    3,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  472,  472,  472,  472,  472,  472

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\Proyecto1.l"
#define INITIAL 0
#line 2 ".\\Proyecto1.l"

#include <stdio.h>


#line 812 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 47 ".\\Proyecto1.l"


#line 966 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 473 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1220 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 50 ".\\Proyecto1.l"
case 2:
YY_RULE_SETUP
#line 50 ".\\Proyecto1.l"
{printf("Etiqueta php\n"); }
	YY_BREAK
case 3:
#line 53 ".\\Proyecto1.l"
case 4:
#line 54 ".\\Proyecto1.l"
case 5:
#line 55 ".\\Proyecto1.l"
case 6:
#line 56 ".\\Proyecto1.l"
case 7:
#line 57 ".\\Proyecto1.l"
case 8:
#line 58 ".\\Proyecto1.l"
case 9:
#line 59 ".\\Proyecto1.l"
case 10:
#line 60 ".\\Proyecto1.l"
case 11:
#line 61 ".\\Proyecto1.l"
case 12:
#line 62 ".\\Proyecto1.l"
case 13:
#line 63 ".\\Proyecto1.l"
case 14:
#line 64 ".\\Proyecto1.l"
case 15:
#line 65 ".\\Proyecto1.l"
case 16:
#line 66 ".\\Proyecto1.l"
case 17:
#line 67 ".\\Proyecto1.l"
case 18:
#line 68 ".\\Proyecto1.l"
case 19:
#line 69 ".\\Proyecto1.l"
case 20:
#line 70 ".\\Proyecto1.l"
case 21:
#line 71 ".\\Proyecto1.l"
case 22:
#line 72 ".\\Proyecto1.l"
case 23:
#line 73 ".\\Proyecto1.l"
case 24:
#line 74 ".\\Proyecto1.l"
case 25:
#line 75 ".\\Proyecto1.l"
case 26:
#line 76 ".\\Proyecto1.l"
case 27:
#line 77 ".\\Proyecto1.l"
case 28:
#line 78 ".\\Proyecto1.l"
case 29:
#line 79 ".\\Proyecto1.l"
case 30:
#line 80 ".\\Proyecto1.l"
case 31:
#line 81 ".\\Proyecto1.l"
case 32:
#line 82 ".\\Proyecto1.l"
case 33:
#line 83 ".\\Proyecto1.l"
case 34:
#line 84 ".\\Proyecto1.l"
case 35:
#line 85 ".\\Proyecto1.l"
case 36:
#line 86 ".\\Proyecto1.l"
case 37:
#line 87 ".\\Proyecto1.l"
case 38:
#line 88 ".\\Proyecto1.l"
case 39:
#line 89 ".\\Proyecto1.l"
case 40:
#line 90 ".\\Proyecto1.l"
case 41:
#line 91 ".\\Proyecto1.l"
case 42:
#line 92 ".\\Proyecto1.l"
case 43:
#line 93 ".\\Proyecto1.l"
case 44:
#line 94 ".\\Proyecto1.l"
case 45:
#line 95 ".\\Proyecto1.l"
case 46:
#line 96 ".\\Proyecto1.l"
case 47:
#line 97 ".\\Proyecto1.l"
case 48:
#line 98 ".\\Proyecto1.l"
case 49:
#line 99 ".\\Proyecto1.l"
case 50:
#line 100 ".\\Proyecto1.l"
case 51:
YY_RULE_SETUP
#line 100 ".\\Proyecto1.l"
{printf("Reservada\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 ".\\Proyecto1.l"
{printf("igual\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 103 ".\\Proyecto1.l"
{printf("igualdad\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 104 ".\\Proyecto1.l"
{printf("llave\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 105 ".\\Proyecto1.l"
{printf("parentesis\n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 106 ".\\Proyecto1.l"
{printf("corchete\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 107 ".\\Proyecto1.l"
{printf("comparacion\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 109 ".\\Proyecto1.l"
{printf("fin_instruccion\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 110 ".\\Proyecto1.l"
{printf("coma\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 111 ".\\Proyecto1.l"
{printf("punto\n"); } 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 112 ".\\Proyecto1.l"
{printf("dos puntos\n"); }
	YY_BREAK
case 62:
#line 115 ".\\Proyecto1.l"
case 63:
#line 116 ".\\Proyecto1.l"
case 64:
#line 117 ".\\Proyecto1.l"
case 65:
#line 118 ".\\Proyecto1.l"
case 66:
#line 119 ".\\Proyecto1.l"
case 67:
YY_RULE_SETUP
#line 119 ".\\Proyecto1.l"
{printf("Op aritmetico\n"); }
	YY_BREAK
case 68:
#line 122 ".\\Proyecto1.l"
case 69:
#line 123 ".\\Proyecto1.l"
case 70:
#line 124 ".\\Proyecto1.l"
case 71:
#line 125 ".\\Proyecto1.l"
case 72:
#line 126 ".\\Proyecto1.l"
case 73:
YY_RULE_SETUP
#line 126 ".\\Proyecto1.l"
{printf("op logica\n"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 128 ".\\Proyecto1.l"
{printf("t bool\n"); }
	YY_BREAK
case 75:
#line 131 ".\\Proyecto1.l"
case 76:
#line 132 ".\\Proyecto1.l"
case 77:
#line 133 ".\\Proyecto1.l"
case 78:
YY_RULE_SETUP
#line 133 ".\\Proyecto1.l"
{printf("t entero\n"); } 
	YY_BREAK
case 79:
#line 136 ".\\Proyecto1.l"
case 80:
YY_RULE_SETUP
#line 136 ".\\Proyecto1.l"
{printf("t decimal\n"); } 
	YY_BREAK
case 81:
#line 139 ".\\Proyecto1.l"
case 82:
YY_RULE_SETUP
#line 139 ".\\Proyecto1.l"
{printf("cadena\n"); }
	YY_BREAK
case 83:
#line 143 ".\\Proyecto1.l"
case 84:
#line 144 ".\\Proyecto1.l"
case 85:
#line 145 ".\\Proyecto1.l"
case 86:
#line 146 ".\\Proyecto1.l"
case 87:
#line 147 ".\\Proyecto1.l"
case 88:
#line 148 ".\\Proyecto1.l"
case 89:
#line 149 ".\\Proyecto1.l"
case 90:
#line 150 ".\\Proyecto1.l"
case 91:
#line 151 ".\\Proyecto1.l"
case 92:
#line 152 ".\\Proyecto1.l"
case 93:
#line 153 ".\\Proyecto1.l"
case 94:
#line 154 ".\\Proyecto1.l"
case 95:
#line 155 ".\\Proyecto1.l"
case 96:
YY_RULE_SETUP
#line 155 ".\\Proyecto1.l"
{printf("variable definida\n"); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 157 ".\\Proyecto1.l"
{printf("variable\n"); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 159 ".\\Proyecto1.l"
{printf("estruct if\n"); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 160 ".\\Proyecto1.l"
{printf("estruct else\n"); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 161 ".\\Proyecto1.l"
{printf("estruct elseif\n"); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 162 ".\\Proyecto1.l"
{printf("estruct while\n"); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 163 ".\\Proyecto1.l"
{printf("estruct do\n"); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 164 ".\\Proyecto1.l"
{printf("estruct for\n"); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 165 ".\\Proyecto1.l"
{printf("estruct foreach\n"); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 166 ".\\Proyecto1.l"
{printf("estruct break\n"); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 167 ".\\Proyecto1.l"
{printf("estruct switch\n"); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 168 ".\\Proyecto1.l"
{printf("estruct case\n"); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 169 ".\\Proyecto1.l"
{printf("estruct include\n"); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 170 ".\\Proyecto1.l"
{printf("estruct continue\n"); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 171 ".\\Proyecto1.l"
{printf("estruct return\n"); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 177 ".\\Proyecto1.l"
{printf("constante\n"); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 180 ".\\Proyecto1.l"
;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 181 ".\\Proyecto1.l"
{printf("No reconocido\t\n"); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 184 ".\\Proyecto1.l"
ECHO;
	YY_BREAK
#line 1388 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 473 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 473 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 472);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 184 ".\\Proyecto1.l"


int yywrap()
{
    return 1;
}
int main(void)
{
    yylex();
    return 0;
}
