#define NO_RECONOCIDO -1
#define p_reservada 1
#define o_aritmetico 2
#define o_logico 3
#define t_logico 4
#define t_entero 5
#define t_real 6
#define t_cadena 7
#define id 8
#define variable 9
#define constante 10
#define e_control 11
#define v_definida 12
#define funcion 13
#define comentario 14
#define igual 15
#define llave 16
#define parentesis 17
#define corchete 18
#define f_instruccion 19
#define punto 20
#define dospuntos 21
#define php_etiqueta 22
#define igualdad 23
#define comparacion 24
#define coma 25
#define basedatos 26
#define campo_db 27